# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Only CI/CT

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      TESTCONTAINERS_CONFIG_FILE: src/test/resources/testcontainers-ci.properties
      DOCKER_HOST: unix:///var/run/docker.sock
      TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
    strategy:
      fail-fast: false
      matrix:
        source:
          - db2
          - mariadb
          - mysql
          - oracle
          - postgres
          - sqlite
          - sqlserver
          - mongo
    name: Integration (${{ matrix.source }})

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Check Docker info
      run: docker info

    - name: Get version
      run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) " >> $GITHUB_ENV

    - name: Integration tests (exclude Oracle cross-version)
      run: mvn -B -q test --file pom.xml -Dtest="org/replicadb/${{ matrix.source }}/*Test,!org/replicadb/oracle/Oracle2OracleCrossVersionLobTest" -Dsurefire.timeout=600

  non_integration:
    runs-on: ubuntu-latest
    name: Non-integration tests
    env:
      TESTCONTAINERS_CONFIG_FILE: src/test/resources/testcontainers-ci.properties
      DOCKER_HOST: unix:///var/run/docker.sock
      TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Check Docker info
      run: docker info

    - name: Get version
      run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) " >> $GITHUB_ENV

    - name: Non-integration tests (exclude Oracle cross-version)
      run: mvn -B -q test --file pom.xml -Dtest="org/replicadb/cli/*Test,org/replicadb/manager/*Test,org/replicadb/config/*Test,org/replicadb/rowset/*Test,org/replicadb/file/*Test,org/replicadb/ReplicaDBTest,!org/replicadb/oracle/Oracle2OracleCrossVersionLobTest"

  package:
    runs-on: ubuntu-latest
    needs:
      - integration
      - non_integration
    name: Package release

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Check Docker info
      run: docker info

    - name: Get version
      run: echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec) " >> $GITHUB_ENV

    - name: Clean Install
      run: |
        export REPLICADB_RELEASE_VERSION=${{ env.version }}
        echo ${REPLICADB_RELEASE_VERSION}  
        mvn clean install -Dmaven.javadoc.skip=true -DskipTests -B -q -P release 
        cp ./target/ReplicaDB-*.jar . 
        mkdir lib
        echo ${REPLICADB_RELEASE_VERSION} 
        cp ./target/lib/* ./lib 
        tar -zcvf ReplicaDB-v${REPLICADB_RELEASE_VERSION}.tar.gz ReplicaDB-*.jar README.md lib conf bin LICENSE 
        zip -r -X ReplicaDB-v${REPLICADB_RELEASE_VERSION}.zip ReplicaDB-*.jar README.md lib conf bin LICENSE 
        ls -lahtr
